global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ratatoskr'
    static_configs:
      - targets: ['ratatoskr:4000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s